name: cs6250-multimodal
channels:
  - defaults
dependencies:
  - python==3.8.10
  - matplotlib
  - pandas
  - scikit-learn
  - tqdm
  - jupyter
  - pytables
  - pip
  - pip:
    - torch
    - torchtext
    - gensim
    - notebook
    - numpy
    - spacy
    - progressbar2
    - https://huggingface.co/kormilitzin/en_core_med7_lg/resolve/main/en_core_med7_lg-any-py3-none-any.whl
  